### PR TITLE
Added randomized CustomBackground Selection

### PR DESCRIPTION
**Pull request by Synirrr**
Please review and advise.

### CODE REVIEW

**Comment by Casimir255** [comment]
Has this been tested?

**Comment by Synirrr** [comment]
> Has this been tested?

Testing right now wanted to get the pull request up to track it. If youd rather I wait before submitting PR I can do that

**Comment by Casimir255** [comment]
Aslong as it works without crashing, and still works with a single image (without rename etc) then I'm good. Ill wait till you can test it before I merge

**Comment by Synirrr** [comment]
Thanks!

**Comment by Synirrr** [comment]
> Aslong as it works without crashing, and still works with a single image (without rename etc) then I'm good. Ill wait till you can test it before I merge

Tested and works with any dds file starting with CustomLoadingBackground

**Pull request merged**
